/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FilterButton from "./FilterButton";
import SortButton from "./SortButton";
import styles from "./CatalogControls.module.css";

const CatalogControls: React.FC = () => {
  return (
    <div className={styles.controlsContainer}>
      <FilterButton />
      <SortButton />
    </div>
  );
};

export default CatalogControls;
